apiVersion: v1
kind: Service
metadata:
  name: node-redis-service-hanane
spec:
  selector:
    app: node-redis-hanane
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-hanane
spec:
  selector:
    app: redis-hanane
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
